import type { Metadata } from "next";
import { Geist, Geist_Mono } from "next/font/google";
import "./globals.css";
import Link from "next/link";
import { getSession } from "@/lib/auth";
import { createServerClient } from "@supabase/ssr";
import { redirect } from "next/navigation";

const geistSans = Geist({
  variable: "--font-geist-sans",
  subsets: ["latin"],
});

const geistMono = Geist_Mono({
  variable: "--font-geist-mono",
  subsets: ["latin"],
});

export const metadata: Metadata = {
  title: "Create Next App",
  description: "Generated by create next app",
};

export default async function RootLayout({
  children,
}: Readonly<{
  children: React.ReactNode;
}>) {
  const session = await getSession();
  const isAuthed = !!session;

  return (
    <html lang="en">
      <body className={`${geistSans.variable} ${geistMono.variable} antialiased`}>        
        <header className="sticky top-0 z-40 w-full h-16 backdrop-blur supports-[backdrop-filter]:bg-background/70 border-b border-black/5 dark:border-white/10">
          <div className="mx-auto max-w-6xl h-full px-4 flex items-center justify-between">
            <div className="flex items-center gap-3">
              <Link href="/" className="inline-flex items-center gap-2 font-semibold tracking-tight">
                <span className="inline-block h-2 w-2 rounded-full bg-emerald-500" />
                <span>Cinna Tracker</span>
              </Link>
            </div>
            <nav className="hidden sm:flex items-center gap-6 text-sm">
              <Link href="/admin" className="hover:opacity-80">Dashboard</Link>
              <Link href="/track" className="hover:opacity-80">Map</Link>
              {!isAuthed ? (
                <Link href="/login" className="hover:opacity-80">Login</Link>
              ) : (
                <form action={async () => { 'use server'; const res = await fetch('/api/auth/logout', { method: 'POST' }); redirect('/login'); }}>
                  <button className="hover:opacity-80" type="submit">Log out</button>
                </form>
              )}
            </nav>
            <div className="sm:hidden">
              <Link href="/admin" className="text-sm underline">Menu</Link>
            </div>
          </div>
        </header>
        <main className="mx-auto max-w-6xl w-full px-4 py-6">
          {children}
        </main>
      </body>
    </html>
  );
}
